### ISSUE TITLE
Getting all solutions

### ISSUE THREAD

**Issue by bahar-tercan** [bhklab/RLOBICO#3]
I am interested in all solutions generated not only the optimal one. How should I set the parameters and how can I print all solutions?
Thanks.

**Comment by clareli9** [comment]
Hi, thank you for the feedback. This method is implemented to solve the (mixed) integer linear programming problems, which is a subset of optimization topics. The target is always to find the optimized solution based on the model, and the literally "all" solutions are infinite sets. Hope it helps.

**Comment by bahar-tercan** [comment]
Thank you for the reply, indeed I am interested in best k solutions.
Kind regards.
